# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    make
  displayName: 'make'
- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'output_file'
    publishLocation: 'Container'
- task: Bash@3
  displayName: 'Push to GitHub'
  inputs:
    targetType: 'inline'
    script: |
      git config --global user.email 'Narayanan.r@partner.gknautomotive.com'
      git config --global user.name 'rnarayanan15-ltts'
      git clone https://github.com/rnarayanan15-ltts/TestPipeline_V1.git
      cd TestPipeline_V1
      cp -r $(Pipeline.Workspace)/drop/* .
      git add .
      git commit -m 'Add build output'
      git push
